#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist
import keyboard

pub = rospy.Publisher('keyboard', String, queue_size=10)
rospy.init_node('keyboard_input', anonymous=True)
rate = rospy.Rate(10) # 10hz
vel_msg = Twist()

def keyboard_input():
    while not rospy.is_shutdown():
        hello_str = "hello world %s" % rospy.get_time()
        rospy.loginfo(hello_str)
        pub.publish(hello_str)
        rate.sleep()

if __name__ == '__main__':
    try:
        keyboard_input()
    except rospy.ROSInterruptException:
        pass